### ISSUE TITLE
preprocessing.py may have a bug(?)

### ISSUE THREAD

**Issue by teshima058** [ehwa009/Co-Speech_Gesture_Generation#1]
Hi, I'm sorry if I'm mistaken.
About the function "run_PCA_train_tgt"  in preprocessing.py,
in the for loop from line 151, the poses that ran PCA are split for each clip and stacked.
[https://github.com/ehwa009/Co-Speech_Gesture_Generation/blob/b15f8b2fb5778857801c9b42de9b5060f5879229/preprocessing.py#L160](https://github.com/ehwa009/Co-Speech_Gesture_Generation/blob/b15f8b2fb5778857801c9b42de9b5060f5879229/preprocessing.py#L160)
When changing index (in line 160), isn't "start=start+l" instead of "start=l" ?
If the present source code, I think only similar sequences are stacked.

**Comment by ehwa009** [comment]
Hi, I coded "lengths" should be a list that contains each length of poses.

**Comment by teshima058** [comment]
"pca_tgt" isn't a list included all poses in all clips ? 
If lengths is [100, 120, 100, 110], it is repeated as follows in line 154:

0. `sel_p = pca_tgt[0:100]`	(start=  0, l=100)
1. `sel_p = pca_tgt[100:220]`	(start=100, l=120)
2. `sel_p = pca_tgt[120:220]`	(start=120, l=100)
3. `sel_p = pca_tgt[100:210]`	(start=100, l= 110)

"sel_p" become a list consisting of poses of almost the same range, and it is stacked to "ori_tgt".
